// <auto-generated />
using System;
using ControleAcessoVeiculos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAcessoVeiculos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ControleAcessoVeiculosDbContext))]
    [Migration("20260826183028_AlignMvpDataModel")]
    partial class AlignMvpDataModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DadosAnteriores")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_anteriores");

                    b.Property<string>("DadosNovos")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_novos");

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Detalhes")
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entidade");

                    b.Property<int>("RegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_acao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_auditorias_data_hora");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditorias_usuario_id");

                    b.HasIndex("Entidade", "RegistroId")
                        .HasDatabaseName("ix_auditorias_entidade_registro_id");

                    b.ToTable("auditorias", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.CategoriaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("TempoValidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_validade_dias");

                    b.HasKey("Id")
                        .HasName("pk_categorias_acesso");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_categorias_acesso_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_acesso_nome");

                    b.ToTable("categorias_acesso", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_categorias_acesso_tempo_validade", "tempo_validade_dias IS NULL OR tempo_validade_dias >= 0");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_perfis_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_perfis_nome");

                    b.ToTable("perfis", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("DocumentoNumero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_numero");

                    b.Property<string>("DocumentoTipo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("documento_tipo");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoVinculo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_vinculo");

                    b.HasKey("Id")
                        .HasName("pk_pessoas");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_pessoas_ativo");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_pessoas_email")
                        .HasFilter("email IS NOT NULL");

                    b.HasIndex("DocumentoTipo", "DocumentoNumero")
                        .IsUnique()
                        .HasDatabaseName("ux_pessoas_documento")
                        .HasFilter("documento_tipo IS NOT NULL AND documento_numero IS NOT NULL");

                    b.ToTable("pessoas", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.PessoaVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("TipoRelacao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_relacao");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_pessoas_veiculos");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_pessoas_veiculos_ativo");

                    b.HasIndex("VeiculoId")
                        .HasDatabaseName("ix_pessoas_veiculos_veiculo_id");

                    b.HasIndex("PessoaId", "VeiculoId", "TipoRelacao")
                        .IsUnique()
                        .HasDatabaseName("ux_pessoas_veiculos_relacao");

                    b.ToTable("pessoas_veiculos", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_pessoas_veiculos_periodo", "data_fim IS NULL OR data_inicio IS NULL OR data_fim >= data_inicio");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.RegistroAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int>("CategoriaAcessoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_acesso_id");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrada");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_saida");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("objetivo");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_acesso");

                    b.HasIndex("AtualizadoPorId")
                        .HasDatabaseName("ix_registros_acesso_atualizado_por_id");

                    b.HasIndex("CategoriaAcessoId")
                        .HasDatabaseName("ix_registros_acesso_categoria_id");

                    b.HasIndex("CriadoPorId")
                        .HasDatabaseName("ix_registros_acesso_criado_por_id");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_registros_acesso_pessoa_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_registros_acesso_status");

                    b.HasIndex("VeiculoId", "DataHoraEntrada")
                        .HasDatabaseName("ix_registros_acesso_veiculo_data_entrada");

                    b.ToTable("registros_acesso", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_registros_acesso_periodo", "data_hora_saida IS NULL OR data_hora_saida >= data_hora_entrada");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.UsoVeiculoInstitucional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtualizadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("atualizado_por_id");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("criado_por_id");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrada");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_saida");

                    b.Property<string>("Itinerario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("itinerario");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<int?>("QuilometragemEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem_entrada");

                    b.Property<int>("QuilometragemSaida")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem_saida");

                    b.Property<int?>("RegistroAcessoId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_acesso_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_usos_veiculos_institucionais");

                    b.HasIndex("AtualizadoPorId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("MotoristaId")
                        .HasDatabaseName("ix_usos_institucionais_motorista_id");

                    b.HasIndex("RegistroAcessoId")
                        .IsUnique()
                        .HasDatabaseName("ux_usos_institucionais_registro_acesso_id")
                        .HasFilter("registro_acesso_id IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_usos_institucionais_status");

                    b.HasIndex("VeiculoId", "DataHoraSaida")
                        .HasDatabaseName("ix_usos_institucionais_veiculo_saida");

                    b.ToTable("usos_veiculos_institucionais", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_usos_veiculos_institucionais_periodo", "data_hora_entrada IS NULL OR data_hora_entrada >= data_hora_saida");

                            t.HasCheckConstraint("ck_usos_veiculos_institucionais_quilometragem", "quilometragem_saida >= 0 AND (quilometragem_entrada IS NULL OR quilometragem_entrada >= quilometragem_saida)");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_usuarios_ativo");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_pessoa_id");

                    b.ToTable("usuarios", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<bool>("EhInstitucional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_institucional");

                    b.Property<string>("IdentificacaoVeiculo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identificacao_veiculo");

                    b.Property<string>("Marca")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_veiculos_ativo");

                    b.HasIndex("EhInstitucional")
                        .HasDatabaseName("ix_veiculos_institucional");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ux_veiculos_placa")
                        .HasFilter("placa IS NOT NULL");

                    b.ToTable("veiculos", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_veiculos_ano", "ano IS NULL OR ano > 0");

                            t.HasCheckConstraint("ck_veiculos_identificacao", "placa IS NOT NULL OR identificacao_veiculo IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditorias_usuarios_usuario_id");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.PessoaVeiculo", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_veiculos_pessoas");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pessoas_veiculos_veiculos");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.RegistroAcesso", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_registros_acesso_usuarios_atualizado_por_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.CategoriaAcesso", null)
                        .WithMany()
                        .HasForeignKey("CategoriaAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_categorias_categoria_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_usuarios_criado_por_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_pessoas_pessoa_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_veiculos_veiculo_id");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.UsoVeiculoInstitucional", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtualizadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usos_institucionais_usuarios_atualizado_por");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usos_institucionais_usuarios_criado_por");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usos_institucionais_motoristas");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.RegistroAcesso", null)
                        .WithOne()
                        .HasForeignKey("ControleAcessoVeiculos.Domain.Entities.UsoVeiculoInstitucional", "RegistroAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usos_institucionais_registros_acesso");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usos_institucionais_veiculos");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_perfil_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_pessoas_pessoa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
