// <auto-generated />
using System;
using ControleAcessoVeiculos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleAcessoVeiculos.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ControleAcessoVeiculosDbContext))]
    partial class ControleAcessoVeiculosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("detalhes");

                    b.Property<int>("RegistroId")
                        .HasColumnType("integer")
                        .HasColumnName("registro_id");

                    b.Property<string>("Tabela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tabela");

                    b.Property<string>("TipoAcao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_acao");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditorias");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_auditorias_data_hora");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditorias_usuario_id");

                    b.HasIndex("Tabela", "RegistroId")
                        .HasDatabaseName("ix_auditorias_tabela_registro_id");

                    b.ToTable("auditorias", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.CategoriaAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("TempoValidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_validade_dias");

                    b.HasKey("Id")
                        .HasName("pk_categorias_acesso");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_categorias_acesso_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_categorias_acesso_nome");

                    b.ToTable("categorias_acesso", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_categorias_acesso_tempo_validade", "tempo_validade_dias >= 0");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_perfis");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_perfis_ativo");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ux_perfis_nome");

                    b.ToTable("perfis", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_pessoas");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_pessoas_ativo");

                    b.HasIndex("Documento")
                        .IsUnique()
                        .HasDatabaseName("ux_pessoas_documento");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_pessoas_email");

                    b.ToTable("pessoas", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.RegistroAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaAcessoId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_acesso_id");

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_entrada");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_saida");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id")
                        .HasName("pk_registros_acesso");

                    b.HasIndex("CategoriaAcessoId")
                        .HasDatabaseName("ix_registros_acesso_categoria_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_registros_acesso_status");

                    b.HasIndex("VeiculoId", "DataHoraEntrada")
                        .HasDatabaseName("ix_registros_acesso_veiculo_data_entrada");

                    b.ToTable("registros_acesso", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_registros_acesso_periodo", "data_hora_saida IS NULL OR data_hora_saida >= data_hora_entrada");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer")
                        .HasColumnName("perfil_id");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_usuarios_ativo");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_email");

                    b.HasIndex("PerfilId")
                        .HasDatabaseName("ix_usuarios_perfil_id");

                    b.HasIndex("PessoaId")
                        .IsUnique()
                        .HasDatabaseName("ux_usuarios_pessoa_id");

                    b.ToTable("usuarios", "dbo");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cor");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<int>("PessoaId")
                        .HasColumnType("integer")
                        .HasColumnName("pessoa_id");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("placa");

                    b.HasKey("Id")
                        .HasName("pk_veiculos");

                    b.HasIndex("Ativo")
                        .HasDatabaseName("ix_veiculos_ativo");

                    b.HasIndex("PessoaId")
                        .HasDatabaseName("ix_veiculos_pessoa_id");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasDatabaseName("ux_veiculos_placa");

                    b.ToTable("veiculos", "dbo", t =>
                        {
                            t.HasCheckConstraint("ck_veiculos_ano", "ano > 0");
                        });
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_auditorias_usuarios_usuario_id");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.RegistroAcesso", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.CategoriaAcesso", null)
                        .WithMany()
                        .HasForeignKey("CategoriaAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_categorias_categoria_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_registros_acesso_veiculos_veiculo_id");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_perfis_perfil_id");

                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_pessoas_pessoa_id");
                });

            modelBuilder.Entity("ControleAcessoVeiculos.Domain.Entities.Veiculo", b =>
                {
                    b.HasOne("ControleAcessoVeiculos.Domain.Entities.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_veiculos_pessoas_pessoa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
